version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  mongoex:
    container_name: mongoex
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
